name: Build Project

on:
  push:
    branches: [ main ]
    
env:
  DOTNET_VERSION: 5.x # The .NET SDK version to use
  NUGET_URL: https://nuget.pkg.github.com/taboo09/index.json
  # secrets.GITHUB_TOKEN works only for public repos
  # for private ones a PAT needs to be created
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ env.NUGET_URL }}
        
    - name: Display all nuget sources
      run: dotnet nuget list source
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run the application
      run: dotnet run
